"""
export.py
=========

Turn a chat session (or a plan comparison) into a self-contained Markdown
document the rep can save, mail, or paste into a CRM note after a call.

Deliberately plain-text Markdown rather than PDF: it needs no extra dependency,
renders correctly in every CRM and mail client, and stays readable even when
nothing renders it at all. The tables the copilot already produces are Markdown,
so they survive the export untouched.

Nothing here touches the model or the network -- it is pure string formatting
over data the app already has.
"""

from __future__ import annotations

from datetime import datetime

TITLE = "# VI Sales Copilot — conversation"

FOOTER = (
    "_Generated by the VI Telecom Sales & Customer-Care Copilot. "
    "Every plan fact above comes from the loaded VI catalogue._"
)

# Shown in the transcript instead of the raw session role names.
SPEAKERS = {"user": "Rep", "assistant": "Copilot"}


def _stamp(when: datetime | None) -> datetime:
    return when or datetime.now()


def conversation_markdown(messages: list[dict], *, mode: str = "",
                          model: str = "", plan_count: int | None = None,
                          when: datetime | None = None) -> str:
    """
    Render the whole conversation as Markdown, with a header recording HOW the
    answers were produced (engine, model, catalogue size). That provenance is
    the point of the export: a saved answer is only trustworthy if you can tell
    which dataset and engine produced it.
    """
    when = _stamp(when)

    lines = [TITLE, "", f"**Exported:** {when:%d %b %Y, %H:%M}"]
    if mode:
        lines.append(f"**Engine:** {mode}" + (f" — `{model}`" if model else ""))
    if plan_count:
        lines.append(f"**Catalogue:** {plan_count} plans")
    lines += ["", "---", ""]

    if not messages:
        lines.append("_No messages in this conversation yet._")
    else:
        for message in messages:
            speaker = SPEAKERS.get(message.get("role", ""), message.get("role", "?"))
            lines += [f"### {speaker}", "", str(message.get("content", "")).strip(), ""]

    lines += ["---", "", FOOTER]
    return "\n".join(lines)


def comparison_markdown(table: str, plan_names: list[str], *,
                        when: datetime | None = None) -> str:
    """Render a side-by-side comparison table as a standalone document."""
    when = _stamp(when)
    return "\n".join([
        "# VI plan comparison",
        "",
        f"**Exported:** {when:%d %b %Y, %H:%M}",
        f"**Plans:** {', '.join(plan_names)}",
        "",
        "---",
        "",
        table,
        "",
        "---",
        "",
        FOOTER,
    ])


def suggested_filename(prefix: str = "vi-copilot", ext: str = "md",
                       when: datetime | None = None) -> str:
    """A timestamped filename so repeated exports never overwrite each other."""
    return f"{prefix}-{_stamp(when):%Y%m%d-%H%M%S}.{ext}"
